# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-04-06 20:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goods_type', to='demo.GoodsType'),
        ),
    ]
