# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-03-25 00:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'db_table': 'company',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('0', '男'), ('1', '女')], max_length=1)),
                ('com_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee', to='demo.Company')),
            ],
            options={
                'db_table': 'employee',
            },
        ),
    ]
