# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-03-22 06:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'db_table': 'class',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=20)),
                ('gender', models.CharField(choices=[('0', 'man'), ('1', 'women')], max_length=1)),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student', to='demo.Class')),
            ],
            options={
                'db_table': 'student',
            },
        ),
    ]
