# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-04-22 01:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='addtime',
        ),
    ]
